import mongoose from 'mongoose'; import dotenv from 'dotenv'; import { Game } from '../models/Game';
dotenv.config();
const GAMES = [
  { name:'sober',    title:'I Am Sober',                category:'substance',  icon:'🌿', color:'#16a34a', description:"Track your sobriety streak with daily pledge commitments.", features:['Streak Tracker','Savings Counter','Milestones','Daily Pledge'], activePlayers:12400, rating:4.8, difficulty:'easy',   estimatedTime:'5-10 min' },
  { name:'forest',   title:'Forest — Stay Focused',    category:'social',     icon:'🌲', color:'#0d9488', description:'Focus for 25 minutes and grow a virtual tree. Leave and it dies.', features:['Focus Timer','Virtual Forest','Tree Growth','Session Coins'], activePlayers:9800,  rating:4.9, difficulty:'medium', estimatedTime:'25 min' },
  { name:'habitica', title:'Habitica',                  category:'behavioral', icon:'⚔️', color:'#7b1fa2', description:'Turn recovery habits into an RPG adventure. Level up your hero!', features:['RPG Character','Level Up System','Boss Battles','Daily Quests'], activePlayers:7300,  rating:4.7, difficulty:'hard',   estimatedTime:'15-20 min' },
  { name:'braver',   title:'Braver',                   category:'pornography',icon:'🧗', color:'#d97706', description:'Decision-based story game. Make strong choices and build willpower.', features:['Story Decisions','Willpower Bar','Daily Check-In','Streak Badges'], activePlayers:5100,  rating:4.6, difficulty:'medium', estimatedTime:'10-15 min' },
  { name:'mindful',  title:'Mindful — Breathing',      category:'mindfulness',icon:'🧘', color:'#0f766e', description:'Guided box breathing and mindfulness exercises to find calm.', features:['Box Breathing','Mindful Exercises','Calm Sessions','Daily Resets'], activePlayers:6200,  rating:4.8, difficulty:'easy',   estimatedTime:'5-15 min' },
  { name:'journal',  title:'Journal — Reflection',     category:'mindfulness',icon:'📓', color:'#be123c', description:'Answer daily prompts, track your mood, and build a journaling streak.', features:['Daily Prompts','Mood Tracking','Journal Streak','Word Goals'], activePlayers:4300,  rating:4.7, difficulty:'easy',   estimatedTime:'10-20 min' },
];
export const seedGames = async () => { for(const g of GAMES) await Game.findOneAndUpdate({name:g.name},{$setOnInsert:g},{upsert:true,new:false}); console.log(`✅ ${GAMES.length} games seeded`); };
if(require.main===module){const uri=process.env.MONGODB_URI||'mongodb://localhost:27017/recovery-portal';mongoose.connect(uri).then(async()=>{await Game.deleteMany({});await seedGames();process.exit(0);}).catch(e=>{console.error(e);process.exit(1);});}
