// =============================================================================
// mockData.ts — Fake counselor data used while the real API is not yet connected.
// When you're ready to go live, delete this file and replace the import in
// page.tsx with a real fetch() call to GET /api/counselors.
// =============================================================================

import { Counselor } from "./types";

// 6 sample counselors covering all specializations and availability states.
// Each entry includes availableSlots so the BookingModal has time options to show.
export const MOCK_COUNSELORS: Counselor[] = [
  {
    id: "1",
    name: "Dr. Sarah Smith",
    title: "Psychologist",
    specialty: ["Addiction", "Trauma"],
    rating: 4.9,
    reviews: 128,
    fee: 80,
    availability: "available_today",
    availableSlots: [
      { time: "09:00", available: true },
      { time: "10:30", available: true },
      { time: "13:00", available: true },
      { time: "14:30", available: false }, // already booked — shown greyed out
      { time: "16:00", available: true },
      { time: "17:30", available: true },
    ],
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "Specializing in addiction recovery with over 10 years of experience helping individuals rebuild their lives.",
    experience: 10,
  },
  {
    id: "2",
    name: "James Carter",
    title: "Clinical Counselor",
    specialty: ["Addiction", "Anxiety"],
    rating: 4.7,
    reviews: 95,
    fee: 70,
    availability: "available_today",
    availableSlots: [
      { time: "08:00", available: true },
      { time: "11:00", available: true },
      { time: "14:00", available: true },
      { time: "15:30", available: false },
      { time: "17:00", available: true },
      { time: "18:30", available: true },
    ],
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    bio: "Certified in substance abuse counseling with a focus on holistic recovery approaches.",
    experience: 7,
  },
  {
    id: "3",
    name: "Dr. Maya Patel",
    title: "Substance Abuse Specialist",
    specialty: ["Addiction", "Family"],
    rating: 4.8,
    reviews: 212,
    fee: 95,
    availability: "next_monday",
    availableSlots: [
      { time: "09:30", available: true },
      { time: "11:00", available: true },
      { time: "13:30", available: true },
      { time: "15:00", available: true },
      { time: "16:30", available: false },
      { time: "18:00", available: true },
    ],
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    bio: "Board-certified specialist in substance use disorders with expertise in family systems therapy.",
    experience: 15,
  },
  {
    id: "4",
    name: "Michael Torres",
    title: "Recovery Coach",
    specialty: ["Trauma", "Anxiety"],
    rating: 4.6,
    reviews: 74,
    fee: 60,
    availability: "next_monday",
    availableSlots: [
      { time: "10:00", available: true },
      { time: "12:00", available: true },
      { time: "14:00", available: true },
      { time: "16:00", available: true },
      { time: "17:30", available: false },
      { time: "19:00", available: true },
    ],
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    bio: "Certified recovery coach with lived experience in addiction, dedicated to peer-based support.",
    experience: 5,
  },
  {
    id: "5",
    name: "Dr. Linda Chen",
    title: "Family Therapist",
    specialty: ["Family", "Trauma"],
    rating: 4.9,
    reviews: 163,
    fee: 90,
    availability: "available_today",
    availableSlots: [
      { time: "08:30", available: true },
      { time: "10:00", available: false },
      { time: "12:30", available: true },
      { time: "14:00", available: true },
      { time: "16:30", available: true },
      { time: "18:00", available: true },
    ],
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    bio: "Licensed family therapist specializing in rebuilding relationships damaged by addiction.",
    experience: 12,
  },
  {
    id: "6",
    name: "Robert Anand",
    title: "Addiction Counselor",
    specialty: ["Addiction", "Anxiety"],
    rating: 4.5,
    reviews: 88,
    fee: 65,
    availability: "next_monday",
    availableSlots: [
      { time: "09:00", available: true },
      { time: "11:30", available: true },
      { time: "13:00", available: false },
      { time: "15:00", available: true },
      { time: "17:00", available: true },
      { time: "18:30", available: true },
    ],
    image: "https://randomuser.me/api/portraits/men/85.jpg",
    bio: "Compassionate counselor with expertise in evidence-based approaches for addiction treatment.",
    experience: 8,
  },
];
